### ISSUE TITLE
correspnding designation does not work

### ISSUE THREAD

**Issue by abduazizR** [kapsner/authors-block#6]
Hi,

First, thank you so much for the nice and helpful extension. It's really cool! I am just wondering why the corresponding option does not work for me with docx files. The equal contribution works and everything is good, but although I put corresponding in the right order

```
---
title: "Cannot share"
subtitle: "Manuscript draft."
authors:
  - name: Abdullah Abdelaziz
    affiliations:
      - ref: c1
    corresponding: true
  - name: cannot share
    affiliations:
      - ref: u1
      - ref: u2
affiliations:
  - id: c1
    name: xxxx
  - id: u1
    name: xxxxxx
  - id: u2
    name: xxxxxxxxx

filters:
  - authors-block
  - docx-landscape.lua  

format:
  docx: 
      output-file: "my manuscript draft"
  pdf: default
editor: visual
csl: jama.csl
reference-doc: custom-reference-doc.docx
bibliography: references.bib
---
```

This is how my header looks like.

Thanks

**Comment by kapsner** [comment]
Hi @abduazizR , thanks for reporting this. Could you please provide me with some additional information so that I can try to reproduce the issue? On which operating system are you working? Which quarto-version are you using?

**Comment by abduazizR** [comment]
Hi @kapsner 

Thank you for the quick response. My operating system is Windows 11, and my Quarto version is 1.3.330

**Comment by kapsner** [comment]
@abduazizR moving to quarto 1.3.* also introduced some issues with the PDF version, which I've fixed on the development branch. Could you please try out, if [this suggestion](https://github.com/kapsner/authors-block/issues/5#issuecomment-1496551635) eventually helps to solve the problem?

**Comment by kapsner** [comment]
I've just merged the quarto 1.3.* enhancements to the main branch so you can just reinstall the extension with the usual command to get the latest version for testing.
Unfortunately, I was not able to reproduce your error on my system with quarto 1.3.336, however, I am also using Linux and have no access to a Windows 11 workstation to check, if the code behaves differently there.

@abduazizR could you please check if the updated version also solves the issue with the missing correspondence for you?

**Comment by abduazizR** [comment]
Thank you for the replies. I tried it now. I run the following the terminal

```
A new release of Deno is available: 1.28.2 → 1.34.0 Run `deno upgrade` to install it.

Quarto extensions may execute code when documents are rendered. If you do not
trust the authors of the extension, we recommend that you do not install or
use the extension.
 ? Do you trust the authors of this extension (Y/n) » Yes
[>] Downloading
[>] Unzipping
    Found 1 extension.

The following changes will be made:
Authors-block   [Update] 0.1.1 -> 0.2.1 (filter)
 ? Would you like to continue (Y/n) » Yes

[>] Extension installation complete.
Learn more about this extension at https://www.github.com/kapsner/authors-block
```

But the problem is not solved

**Comment by kapsner** [comment]
Hmm, strange. I am sorry for that. Unfortunately, I am unable to reproduce the issue. Could you please retry with a minimal header to rule out that is has something to do with the other filter or the reference doc:

```yaml
---
title: "Cannot share"
subtitle: "Manuscript draft."
authors:
  - name: Abdullah Abdelaziz
    affiliations:
      - ref: c1
    corresponding: true
  - name: cannot share
    affiliations:
      - ref: u1
      - ref: u2
affiliations:
  - id: c1
    name: xxxx
  - id: u1
    name: xxxxxx
  - id: u2
    name: xxxxxxxxx

filters:
  - authors-block

format:
  docx: 
      output-file: "my manuscript draft"
  native: default
---
```

Could you also please post the content of the "native" file (also in the modified header as additional format)?

**Comment by abduazizR** [comment]
I tried it but the problem persists
![image](https://github.com/kapsner/authors-block/assets/61837330/88ce698d-a383-46c4-88bd-c06cc4ef56b3)

**Comment by kapsner** [comment]
Please add an email address to the entry of the corresponding author and retry.

```yaml
---
title: "Cannot share"
subtitle: "Manuscript draft."
authors:
  - name: Abdullah Abdelaziz
    affiliations:
      - ref: c1
    corresponding: true
    email: test@abcde.org
  - name: cannot share
    affiliations:
      - ref: u1
      - ref: u2
affiliations:
  - id: c1
    name: xxxx
  - id: u1
    name: xxxxxx
  - id: u2
    name: xxxxxxxxx

filters:
  - authors-block

format:
  docx: 
      output-file: "my manuscript draft"
  native: default
---
```

**Comment by kapsner** [comment]
Thank you very much for your efforts. Perhaps I've found the issue. In your example is the email address missing, which, however, is required for the corresponding part. Could you please add an email address to the entry of the corresponding author and retry?

```yaml
---
title: "Cannot share"
subtitle: "Manuscript draft."
authors:
  - name: Abdullah Abdelaziz
    affiliations:
      - ref: c1
    corresponding: true
    email: test@abcde.org
  - name: cannot share
    affiliations:
      - ref: u1
      - ref: u2
affiliations:
  - id: c1
    name: xxxx
  - id: u1
    name: xxxxxx
  - id: u2
    name: xxxxxxxxx

filters:
  - authors-block

format:
  docx: 
      output-file: "my manuscript draft"
  native: default
---
```

**Comment by abduazizR** [comment]
It worked!! 
Thank you so much for working with me on this.

**Comment by kapsner** [comment]
Perfect, glad to hear that it works now!
